name: Publish & Release

permissions:
  contents: write

on:
  push:
    branches:
      - main

jobs:
  publish-addon:
    name: Release & Publish
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18.x'
        registry-url: 'https://registry.npmjs.org'

    - name: Install dependencies
      run: |
        npm install
        npm install -g c3addon

    - id: check
      uses: EndBug/version-check@v1
      with:
        file-name: singleGlobalPlugin/addon.json
        diff-search: true
        token: ${{ secrets.GITHUB_TOKEN }}

    - name: Generate .c3addon file for upload
      if: steps.check.outputs.changed == 'true'
      run: npx c3addon pack --root singleGlobalPlugin

    - name: Release
      if: steps.check.outputs.changed == 'true'
      uses: softprops/action-gh-release@v1
      with:
        tag_name: ${{ steps.check.outputs.version }}
        prerelease: false
        files: MyCompany_SingleGlobal.c3addon

    - name: Release
      if: steps.check.outputs.changed == 'true'
      run: 'c3addon publish'
      with:
        # Use "secrets" from repository settings page
        auth-user: ${{ secrets.C3_AUTH_USER }}
        auth-password: ${{ secrets.C3_AUTH_PASSWORD }}

        # Addon URL and file to upload
        addon-url: https://www.construct.net/en/make-games/addons/1057/testing-auto-release/
        upload-file: MyCompany_SingleGlobal.c3addon
        version: ${{ steps.check.outputs.version }}
        release-notes: Released via GitHub Actions
